version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tiny_db
      MYSQL_USER: tiny
      MYSQL_PASSWORD: tiny_pass
    ports:
      - "3306:3306"
